export enum ExpenseCategory {
  SALARY = 'SALARY',
  OFFICE_RENT = 'OFFICE_RENT',
  ELECTRICITY_BILL = 'ELECTRICITY_BILL',
  INTERNET_PHONE_BILL = 'INTERNET_PHONE_BILL',
  OFFICE_SUPPLIES = 'OFFICE_SUPPLIES',
  TRANSPORTATION = 'TRANSPORTATION',
  FOOD_REFRESHMENTS = 'FOOD_REFRESHMENTS',
  EQUIPMENT_MAINTENANCE = 'EQUIPMENT_MAINTENANCE',
  SOFTWARE_SUBSCRIPTIONS = 'SOFTWARE_SUBSCRIPTIONS',
  MARKETING_ADVERTISING = 'MARKETING_ADVERTISING',
  EMPLOYEE_ADVANCE = 'EMPLOYEE_ADVANCE',
  INVESTOR_PAYMENT = 'INVESTOR_PAYMENT',
  PURCHASE_ORDER_PAYMENT = 'PURCHASE_ORDER_PAYMENT',
  RAW_MATERIALS = 'RAW_MATERIALS',
  PACKAGING = 'PACKAGING',
  SHIPPING_LOGISTICS = 'SHIPPING_LOGISTICS',
  TAXES_FEES = 'TAXES_FEES',
  INSURANCE = 'INSURANCE',
  PROFESSIONAL_SERVICES = 'PROFESSIONAL_SERVICES',
  MISCELLANEOUS = 'MISCELLANEOUS',
}

/** Human-readable labels for expense categories */
export const expenseCategoryLabels: Record<ExpenseCategory, string> = {
  [ExpenseCategory.SALARY]: 'Salary',
  [ExpenseCategory.OFFICE_RENT]: 'Office Rent',
  [ExpenseCategory.ELECTRICITY_BILL]: 'Electricity Bill',
  [ExpenseCategory.INTERNET_PHONE_BILL]: 'Internet / Phone Bill',
  [ExpenseCategory.OFFICE_SUPPLIES]: 'Office Supplies',
  [ExpenseCategory.TRANSPORTATION]: 'Transportation',
  [ExpenseCategory.FOOD_REFRESHMENTS]: 'Food & Refreshments',
  [ExpenseCategory.EQUIPMENT_MAINTENANCE]: 'Equipment Maintenance',
  [ExpenseCategory.SOFTWARE_SUBSCRIPTIONS]: 'Software Subscriptions',
  [ExpenseCategory.MARKETING_ADVERTISING]: 'Marketing & Advertising',
  [ExpenseCategory.EMPLOYEE_ADVANCE]: 'Employee Advance',
  [ExpenseCategory.INVESTOR_PAYMENT]: 'Investor Payment',
  [ExpenseCategory.PURCHASE_ORDER_PAYMENT]: 'Purchase Order Payment',
  [ExpenseCategory.RAW_MATERIALS]: 'Raw Materials',
  [ExpenseCategory.PACKAGING]: 'Packaging',
  [ExpenseCategory.SHIPPING_LOGISTICS]: 'Shipping & Logistics',
  [ExpenseCategory.TAXES_FEES]: 'Taxes & Fees',
  [ExpenseCategory.INSURANCE]: 'Insurance',
  [ExpenseCategory.PROFESSIONAL_SERVICES]: 'Professional Services',
  [ExpenseCategory.MISCELLANEOUS]: 'Miscellaneous',
};

/** Categories that are auto-generated by the system (user should not manually select) */
export const AUTO_GENERATED_CATEGORIES: ExpenseCategory[] = [
  ExpenseCategory.SALARY,
  ExpenseCategory.EMPLOYEE_ADVANCE,
  ExpenseCategory.INVESTOR_PAYMENT,
  ExpenseCategory.PURCHASE_ORDER_PAYMENT,
];

/** Categories available for manual expense creation */
export const manualExpenseCategories = Object.values(ExpenseCategory).filter(
  (cat) => !AUTO_GENERATED_CATEGORIES.includes(cat)
);

export enum PaymentMethod {
  CASH = 'CASH',
  BANK_TRANSFER = 'BANK_TRANSFER',
  CHEQUE = 'CHEQUE',
  CARD = 'CARD'
}

export enum ExpenseStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED'
}

// Request Types
export interface CreateExpenseRequest {
  title: string;
  description?: string;
  amount: number;
  category: ExpenseCategory;
  expenseDate: string; // ISO string
  paymentMethod: PaymentMethod;
  status: ExpenseStatus;
  notes?: string;
}

export interface UpdateExpenseRequest {
  title?: string;
  description?: string;
  amount?: number;
  category?: ExpenseCategory;
  expenseDate?: string; // ISO string
  paymentMethod?: PaymentMethod;
  status?: ExpenseStatus;
  notes?: string;
}

export interface GetExpensesParams {
  skip?: number;
  take?: number;
  search?: string;
  category?: ExpenseCategory;
  startDate?: string; // ISO string
  endDate?: string; // ISO string
  status?: ExpenseStatus;
}

// Response Types
export interface ExpenseResponse {
  id: string;
  title: string;
  description?: string;
  amount: number;
  category: ExpenseCategory;
  expenseDate: string;
  paymentMethod: PaymentMethod;
  status: ExpenseStatus;
  notes?: string;
  recordedBy: string;
  userName?: string;
  isAutoGenerated?: boolean;
  salaryId?: string;
  employeeAdvanceId?: string;
  investorPaymentId?: string;
  purchaseOrderPaymentId?: string;
  createdAt: string;
  updatedAt: string;
}

export interface ExpensesListResponse {
  expenses: ExpenseResponse[];
  total: number;
}

export interface ExpenseStatisticsResponse {
  total: number;
  transactionCount: number;
  approved: number;
  pending: number;
  average: number;
}

export interface MonthlyTrendResponse {
  month: string; // Format: "YYYY-MM"
  amount: number;
}

export interface CategorySummaryResponse {
  category: ExpenseCategory;
  total: number;
  count: number;
  percentage: number;
}